#version 440 core

layout(local_size_x = 8, local_size_y = 8) in;
layout(r32ui, binding=2) uniform uimage2D headPointerTexImage;

struct ABufferNode
{
    vec4 color;
    vec4 position;
    uint next;
};

layout(std430, binding=0) buffer ABufferStorage
{
    ABufferNode nodes[];
};

// 假设工具的纹理是不透明纹理
uniform sampler3D opaqueDepthTex;
uniform sampler3D toolOldTex;
uniform sampler3D toolNewTex;

uniform ivec2 windowSize;
uniform int maxLayer;

layout(rgba16f, binding = 4) uniform image2D outputColor;
// layout(r16f, binding = 3) image2D outputDepth;

void swapBufferNode(in bufferNode[64], int firstIndex, int secondIndex)
{
    ABufferNode node = bufferNode[firstIndex];
    bufferNode[firstIndex].color = bufferNode[secondIndex].color;
    bufferNode[firstIndex].position = bufferNode[secondIndex].position;
    bufferNode[firstIndex].next = bufferNode[secondIndex].next;

    bufferNode[secondIndex].color = node.color;
    bufferNode[secondIndex].position = node.position;
    bufferNode[secondIndex].next = node.next;
}
void sortFragments(inout bufferNode[64], int fragmentCount)
{
    for(int i = fragmentCount - 1; i > 0; i--){
        bool swaped = false;
        for(int j = 0; j < i; j++){
            if(bufferNode[j].next > bufferNode[j+1].next)
            {
                swapBufferNode(bufferNode, j, j+1);
                swaped = true;
            }
        }
        if (!swaped)
        {
            return;
        }
    }
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

    if(coord.x >= windowSize.x || coord.y >= windowSize.y)
    {
        return;
    }

    ABufferNode fragments[64];
    int fragmentCount = 0;
    uint currentNode = imageLoad(headPointerTexImage, coord).r;

    while(currentNode != 0xffffffff && fragmentCount < maxLayer)
    {
        fragments[fragmentCount] = nodes[currentNode];
        currentNode = nodes[currentNode].next;
        fragmentCount++;
    }

    if (fragmentCount == 0)
    {
        return;
    }

    sortFragments(fragments, fragmentCount);

    if(fragmentCount == 0)
    {
        imageStore(outputColor, coord, vec4(1, 1, 0, 1));
        // imageStore(outputDepth, coord, vec4(0));
    }
    else
    {
        imageStore(outputColor, coord, vec4(fragmentCount * 1.0 / 10, 0.0, 0.0, 1.0));
    }

    // if (fragmentCount == 1)
    // {
    //     imageStore(outputColor, coord, vec4(1.0, 0.0, 0.0, 1.0));
    // }

    // if (fragmentCount == 3)
    // {
    //     imageStore(outputColor, coord, vec4(0, 1, 0, 1));
    // }
    // if (fragmentCount == 5)
    // {
    //     imageStore(outputColor, coord, vec4(0, 0, 1, 1));
    // }
}
